"""initial schema with RBAC role

Revision ID: 3fc11366dcd0
Revises: 
Create Date: 2026-09-02 19:24:39.867415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc11366dcd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('encryption_algorithm', sa.String(length=50), nullable=True))
    op.add_column('files', sa.Column('key_algorithm', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default='USER'))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_column('files', 'key_algorithm')
    op.drop_column('files', 'encryption_algorithm')
    # ### end Alembic commands ###
